service: product-service

frameworkVersion: '3'

plugins:
  - serverless-auto-swagger
  
provider:
  name: aws
  runtime: nodejs16.x
  environment:
    PRODUCTS_TABLE: 'Products_aws_table'
    STOCKS_TABLE: 'Stocks_aws_table'
    SQS_URL:
      Ref: catalogItemsQueue
    SNS_ARN: 
      Ref: createProductTopicSnS

  iamRoleStatements:
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: createProductTopicSnS 

resources:
  Resources:
    catalogItemsQueue:
     Type: AWS::SQS::Queue
     Properties:
       QueueName: catalogItemsQueue-product-service
    createProductTopicSnS:
     Type: AWS::SNS::Topic
     Properties:
       TopicName: createProductTopicSnS-product-service
    snsSubscription:
     Type: AWS::SNS::Subscription
     Properties: 
       Endpoint: margaritka1992@gmail.com
       Protocol: email
       TopicArn: !Ref 'createProductTopicSnS'

functions:
  getProductsList:
    handler: getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get

  getProductsById:
    handler: getProductsListById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get

  createProduct:
    handler: createProduct.createProduct
    events:
      - httpApi:
          path: /products
          method: post

  catalogBatchProcess:
    handler: catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - catalogItemsQueue
              - Arn
