service: product-service

frameworkVersion: '3'

plugins:
  - serverless-auto-swagger
  
provider:
  name: aws
  runtime: nodejs12.x


functions:
  getProductsList:
    handler: getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get

  getProductsById:
    handler: getProductsListById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get


