service: import-service

frameworkVersion: '3'

plugins:
  - serverless-auto-swagger

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  environment:
    UPLOADED_BUCKET: 'shaduryna-5-task'
    SQS_URL: 'https://sqs.us-east-1.amazonaws.com/348684423546/catalogItemsQueue-product-service'
  deploymentBucket:
    name: shaduryna-5-task
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::shaduryna-5-task"
    - Effect: "Allow"
      Action: 
        - "s3:*"
      Resource:
        - "arn:aws:s3:::shaduryna-5-task/*"
  httpApi:
    cors: true
    authorizers:
      customAuthorizer:
        type: request
        functionArn: arn:aws:lambda:us-east-1:348684423546:function:authorization-service-dev-basicAuthorizer
        enableSimpleResponses: true

functions:
  importProductsFile:
    handler: importProducts.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get    
          authorizer:
            name: customAuthorizer
            type: request

  importFileParser:
    handler: importFileParser.fileParser
    events:
      - s3:
          bucket: 'shaduryna-5-task'
          event: s3:ObjectCreated:*
          rules:
            - prefix: "uploaded/"
          existing: true


